name = "gepetinho"
compatibility_date = "2023-12-01"
workers_dev = true

[site]
bucket = "out"

[build]
command = "npm run build"
upload.format = "directory"

[[d1_databases]]
binding = "DB"
database_name = "gepetinho-db"
database_id = "70291398-2836-4c13-9de8-5b35161c56e2"

[env.production]
routes = [
  { pattern = "/api/*", zone_id = "" },
  { pattern = "*/*", zone_id = "" }
]

[vars]
# Add your OpenAI API key in the Cloudflare dashboard
OPENAI_API_KEY = ""
JWT_SECRET = "theo1234" 